INSERT INTO hospital (hospital_name, country, region, town) VALUES
('C.H. Ciudad de Jaén','España', 'Andalucía', 'Jaén'),
('Corporació Sanitària Parc Taulí','España', 'Cataluña', 'Sabadell'),
('Hospital 12 Octubre','España', 'Madrid', 'Madrid'),
('Hospital A Coruña','España', 'Galicia', 'A Coruña'),
('Hospital Álava','España', 'País Vasco', 'Vitoria'),
('Hospital Bellvitge','España', 'Cataluña', 'Barcelona'),
('Hospital Cabueñes','España', 'Asturias', 'Gijón'),
('Hospital Clínico Lozano Blesa','España', 'Aragón', 'Zaragoza'),
('Hospital Clinic','España', 'Cataluña', 'Barcelona'),
('Hospital de Burgos','España', 'Castilla y León', 'Burgos'),
('Hospital de Castellón','España', 'Comunidad Valenciana', 'Castellón'),
('Hospital de Guadalajara','España', 'Castilla La Mancha', 'Guadalajara'),
('Hospital de Jerez','España','Andalucía', 'Jerez'),
('Hospital de La Fé','España','Comunidad Valenciana','Valencia'),
('Hospital de Pontevedra','España','Galicia','Pontevedra'),
('Hospital de Salamanca','España','Castilla y León', 'Salamanca'),
('Hospital de Jerez','España','Andalucía', 'Jerez'),
('Hospital Doctor Negrín','España','Canarias', 'Las Palmas de Gran Canaria'),
('Hospital General de Valencia','España','Comunidad Valenciana', 'Valencia'),
('Hospital Germans Trias i Pujol','España','Cataluña', 'Barcelona'),
('Hospital Getafe','España','Madrid', 'Getafe'),
('Hospital La Princesa','España','Madrid', 'Madrid'),
('Hospital Manacor','España','Baleares', 'Manacor'),
('Hospital Marqués de Valdecilla','España','Cantabria', 'Santander'),
('Hospital Miguel Servet','España','Aragón', 'Zaragoza'),
('Hospital Mutua de Terrasa','España','Cataluña', 'Terrasa'),
('Hospital Puerta del Mar','España','Andalucía', 'Cádiz'),
('Hospital Ramón y Cajal','España','Madrid', 'Madrid'),
('Hospital Reina Sofía','España','Madrid', 'Madrid'),
('Hospital Royo Villanova','España','Aragón', 'Zaragoza'),
('Hospital Santa Creu i Sant Pau','España','Cataluña', 'Barcelona'),
('Hospital Santiago de Compostela','España','Galicia', 'Santiago de Compostela'),
('Hospital Son Llàtzer','España','Baleares', 'Palma'),
('Hospital Vall d´Hebron','España','Cataluña', 'Barcelona'),
('Hospital Virgen Arrixaca','España','Murcia', 'Murcia'),
('Hospital Virgen de la Macarena','España','Andalucía', 'Sevilla');

INSERT INTO sample_type (sample) VALUES
('Esputo'),
('Esputo(FQ)'),
('Líquido pleural'),
('Líquido peritoneal'),
('Orina'),
('Sangre'),
('Broncoaspirado'),
('Absceso'),
('Exudado cutáneo'),
('Exudado ótico'),
('Exudado quemadura'),
('Exudado herida'),
('Exudado herida'),
('Exudado conjuntival'),
('Exudado herida quirúrgica'),
('Exudado otros'),
('Biopsia cutánea'),
('Prótesis'),
('Raspado córneal'),
('Aspirado traqueal'),
('Biopsia ósea'),
('Úlcera'),
('Líquido articular'),
('Catéter'),
('Lavado broncoalveolar'),
('Aspirado nasofaringeo'),
('Lavado Broncoalveolar'),
('Cepillado bronquial'),
('Biopsia otros'),
('Líquido estéril otros'),
('Otros');

INSERT INTO sequencing_platform (sequencing_platform_name, sequencing_platform_supplier) VALUES 
('Illumina MiSeq', 'Illumina'),
('Illumina NovaSeq', 'Illumina'),
('Oxford Nanopore MinION', 'Oxford Nanopore Technologies'),
('Oxford Nanopore GridION', 'Oxford Nanopore Technologies');

INSERT INTO sequencing_technology (sequencing_technology_name, reads_type) VALUES 
('Illumina Sequencing', 'Short Read'),
('Illumina NovaSeq', 'Short Read'),
('Illumina MiSeq', 'Short Read'),
('Illumina HiSeq', 'Short Read'),
('Oxford Nanopore Sequencing', 'Long Read'),
('Oxford Nanopore MinION', 'Long Read'),
('Oxford Nanopore GridION', 'Long Read');

INSERT INTO sequencing_library (sequencing_library_method) VALUES 
('WGS Library'),
('Exome Library'),
('RNA Library'),
('ChIP Library'),
('Methyl-seq Library'),
('Amplicon Library'),
('Metagenomic Library'),
('Targeted Library'),
('Whole Transcriptome Library'),
('cDNA Library'),
('Shotgun Library'),
('RAD Library'),
('Paired-End Library'),
('Single-Cell Library'),
('Long-Read Library'),
('Short-Read Library'),
('PCR-free Library'),
('Mate-Pair Library'),
('3\' Tag Library'),
('5\' Tag Library'),
('Full-length Library'),
('Strand-specific Library'),
('Synthetic Long-Read Library'),
('Circularized Library'),
('Size-Selected Library'),
('Normalized Library'),
('Low-Input Library'),
('Direct-capture Library'),
('Tethered-capture Library'),
('Capture-Hi-C Library');

INSERT INTO flowcell_kit (flowcell_kit_name) VALUES 
('flowcell_kit_name_1'),
('flowcell_kit_name_2'),
('flowcell_kit_name_3');

INSERT INTO mutational_resistome (locus, official_name, synonym_name, pbp_name, species) VALUES 
('PA0004', 'gyrB', '', '', 'Pseudomonas aeruginosa'),
('PA0005', 'lptA', '', '', 'Pseudomonas aeruginosa'),
('PA0018', 'fmt', '', '', 'Pseudomonas aeruginosa'),
('PA0058', 'dsbM', '', '', 'Pseudomonas aeruginosa'),
('PA0301', 'spuE', '', '', 'Pseudomonas aeruginosa'),
('PA0302', 'spuF', '', '', 'Pseudomonas aeruginosa'),
('PA0392', 'yggT', '', '', 'Pseudomonas aeruginosa'),
('PA0402', 'pyrB', '', '', 'Pseudomonas aeruginosa'),
('PA0424', 'mexR', '', '', 'Pseudomonas aeruginosa'),
('PA0425', 'mexA', '', '', 'Pseudomonas aeruginosa'),
('PA0426', 'mexB', '', '', 'Pseudomonas aeruginosa'),
('PA0427', 'oprM', '', '', 'Pseudomonas aeruginosa'),
('PA0463', 'creB', '', '', 'Pseudomonas aeruginosa'),
('PA0464', 'creC', '', '', 'Pseudomonas aeruginosa'),
('PA0465', 'creD', '', '', 'Pseudomonas aeruginosa'),
('PA0486', 'yihE', '', '', 'Pseudomonas aeruginosa'),
('PA0487', 'modR', '', '', 'Pseudomonas aeruginosa'),
('PA0610', 'prtN', '', '', 'Pseudomonas aeruginosa'),
('PA0611', 'prtR', '', '', 'Pseudomonas aeruginosa'),
('PA0612', 'ptrB', '', '', 'Pseudomonas aeruginosa'),
('PA0779', 'asrA', '', '', 'Pseudomonas aeruginosa'),
('PA0807', 'ampDh3', '', '', 'Pseudomonas aeruginosa'),
('PA0869', '', '', 'PBP7', 'Pseudomonas aeruginosa'),
('PA0893', 'argR', '', '', 'Pseudomonas aeruginosa'),
('PA0958', 'oprD', '', '', 'Pseudomonas aeruginosa'),
('PA1178', 'oprH', '', '', 'Pseudomonas aeruginosa'),
('PA1179', 'phoP', '', '', 'Pseudomonas aeruginosa'),
('PA1180', 'phoQ', '', '', 'Pseudomonas aeruginosa'),
('PA1343', 'pagP', '', '', 'Pseudomonas aeruginosa'),
('PA1345', 'gshB', '', '', 'Pseudomonas aeruginosa'),
('PA1375', 'pdxB', '', '', 'Pseudomonas aeruginosa'),
('PA1409', 'aphA', '', '', 'Pseudomonas aeruginosa'),
('PA1430', 'lasR', '', '', 'Pseudomonas aeruginosa'),
('PA1588', 'sucC', '', '', 'Pseudomonas aeruginosa'),
('PA1589', 'sucD', '', '', 'Pseudomonas aeruginosa'),
('PA1777', 'oprF', '', '', 'Pseudomonas aeruginosa'),
('PA1796', 'folD', '', '', 'Pseudomonas aeruginosa'),
('PA1797', '', '', '-', 'Pseudomonas aeruginosa'),
('PA1798', 'parS', '', '', 'Pseudomonas aeruginosa'),
('PA1799', 'parR', '', '', 'Pseudomonas aeruginosa'),
('PA1801', 'clpP', '', '', 'Pseudomonas aeruginosa'),
('PA1803', 'lon', '', '', 'Pseudomonas aeruginosa'),
('PA1812', 'mltD', '', '', 'Pseudomonas aeruginosa'),
('PA1886', 'polB', '', '', 'Pseudomonas aeruginosa'),
('PA2006', '', '', '-', 'Pseudomonas aeruginosa'),
('PA2018', 'mexY', '', '', 'Pseudomonas aeruginosa'),
('PA2019', 'mexX', '', '', 'Pseudomonas aeruginosa'),
('PA2020', 'mexZ', '', '', 'Pseudomonas aeruginosa'),
('PA2023', 'galU', '', '', 'Pseudomonas aeruginosa'),
('PA2050', '', '', '-', 'Pseudomonas aeruginosa'),
('PA2071', 'fusA2', '', '', 'Pseudomonas aeruginosa'),
('PA2227', 'vqsM', '', '', 'Pseudomonas aeruginosa'),
('PA2272', '', '', 'PBP3a', 'Pseudomonas aeruginosa'),
('PA2273', 'soxR', '', '', 'Pseudomonas aeruginosa'),
('PA2489', '', '', '-', 'Pseudomonas aeruginosa'),
('PA2490', 'ydbB', '', '', 'Pseudomonas aeruginosa'),
('PA2491', 'mexS', '', '', 'Pseudomonas aeruginosa'),
('PA2492', 'mexT', '', '', 'Pseudomonas aeruginosa'),
('PA2493', 'mexE', '', '', 'Pseudomonas aeruginosa'),
('PA2494', 'mexF', '', '', 'Pseudomonas aeruginosa'),
('PA2495', 'oprN', '', '', 'Pseudomonas aeruginosa'),
('PA2522', 'czcC', '', '', 'Pseudomonas aeruginosa'),
('PA2523', 'czcR', '', '', 'Pseudomonas aeruginosa'),
('PA2524', 'czcS', '', '', 'Pseudomonas aeruginosa'),
('PA2525', 'opmB', '', '', 'Pseudomonas aeruginosa'),
('PA2526', 'muxC', '', '', 'Pseudomonas aeruginosa'),
('PA2527', 'muxB', '', '', 'Pseudomonas aeruginosa'),
('PA2528', 'muxA', '', '', 'Pseudomonas aeruginosa'),
('PA2615', 'ftsK', '', '', 'Pseudomonas aeruginosa'),
('PA2621', 'clpS', '', '', 'Pseudomonas aeruginosa'),
('PA2642', 'nuoG', '', '', 'Pseudomonas aeruginosa'),
('PA2649', 'nuoN', '', '', 'Pseudomonas aeruginosa'),
('PA2797', '', '', '-', 'Pseudomonas aeruginosa'),
('PA2798', '', '', '-', 'Pseudomonas aeruginosa'),
('PA2809', 'copR', '', '', 'Pseudomonas aeruginosa'),
('PA2810', 'copS', '', '', 'Pseudomonas aeruginosa'),
('PA2830', 'htpX', '', '', 'Pseudomonas aeruginosa'),
('PA3005', 'nagZ', '', '', 'Pseudomonas aeruginosa'),
('PA3013', 'foaB', '', '', 'Pseudomonas aeruginosa'),
('PA3014', 'faoA', '', '', 'Pseudomonas aeruginosa'),
('PA3047', '', '', 'PBP4', 'Pseudomonas aeruginosa'),
('PA3050', 'pyrD', '', '', 'Pseudomonas aeruginosa'),
('PA3077', 'cprR', '', '', 'Pseudomonas aeruginosa'),
('PA3078', 'cprS', '', '', 'Pseudomonas aeruginosa'),
('PA3141', 'capD', '', '', 'Pseudomonas aeruginosa'),
('PA3168', 'gyrA', '', '', 'Pseudomonas aeruginosa'),
('PA3521', 'opmE', '', '', 'Pseudomonas aeruginosa'),
('PA3522', 'mexQ', '', '', 'Pseudomonas aeruginosa'),
('PA3523', 'mexP', '', '', 'Pseudomonas aeruginosa'),
('PA3533', 'grxD', '', '', 'Pseudomonas aeruginosa'),
('PA3574', 'nalD', '', '', 'Pseudomonas aeruginosa'),
('PA3602', 'yerD', '', '', 'Pseudomonas aeruginosa'),
('PA3676', 'mexK', '', '', 'Pseudomonas aeruginosa'),
('PA3677', 'mexJ', '', '', 'Pseudomonas aeruginosa'),
('PA3678', 'mexL', '', '', 'Pseudomonas aeruginosa'),
('PA3719', 'armR', '', '', 'Pseudomonas aeruginosa'),
('PA3721', 'nalC', '', '', 'Pseudomonas aeruginosa'),
('PA3999', '', '', 'PBP5/6', 'Pseudomonas aeruginosa'),
('PA4001', 'sltB1', '', '', 'Pseudomonas aeruginosa'),
('PA4003', '', '', 'PBP2', 'Pseudomonas aeruginosa'),
('PA4020', 'mpl', '', '', 'Pseudomonas aeruginosa'),
('PA4069', '', '', '-', 'Pseudomonas aeruginosa'),
('PA4109', 'ampR', '', '', 'Pseudomonas aeruginosa'),
('PA4110', 'ampC', '', '', 'Pseudomonas aeruginosa'),
('PA4119', 'aph', '', '', 'Pseudomonas aeruginosa'),
('PA4205', 'mexG', '', '', 'Pseudomonas aeruginosa'),
('PA4206', 'mexH', '', '', 'Pseudomonas aeruginosa'),
('PA4207', 'mexI', '', '', 'Pseudomonas aeruginosa'),
('PA4208', 'opmD', '', '', 'Pseudomonas aeruginosa'),
('PA4218', 'ampP', '', '', 'Pseudomonas aeruginosa'),
('PA4238', 'rpoA', '', '', 'Pseudomonas aeruginosa'),
('PA4260', 'rplB', '', '', 'Pseudomonas aeruginosa'),
('PA4266', 'fusA1', '', '', 'Pseudomonas aeruginosa'),
('PA4269', 'rpoC', '', '', 'Pseudomonas aeruginosa'),
('PA4270', 'rpoB', '', '', 'Pseudomonas aeruginosa'),
('PA4273', 'rplA', '', '', 'Pseudomonas aeruginosa'),
('PA4315', 'mvaT', '', '', 'Pseudomonas aeruginosa'),
('PA4374', 'mexV', '', '', 'Pseudomonas aeruginosa'),
('PA4375', 'mexW', '', '', 'Pseudomonas aeruginosa'),
('PA4380', 'colS', '', '', 'Pseudomonas aeruginosa'),
('PA4381', 'colR', '', '', 'Pseudomonas aeruginosa'),
('PA4393', 'ampG', '', '', 'Pseudomonas aeruginosa'),
('PA4406', 'lpxC', '', '', 'Pseudomonas aeruginosa'),
('PA4418', '', '', 'PBP3', 'Pseudomonas aeruginosa'),
('PA4444', 'mltB1', '', '', 'Pseudomonas aeruginosa'),
('PA4462', 'rpoN', '', '', 'Pseudomonas aeruginosa'),
('PA4521', 'ampE', '', '', 'Pseudomonas aeruginosa'),
('PA4522', 'ampD', '', '', 'Pseudomonas aeruginosa'),
('PA4567', 'rpmA', '', '', 'Pseudomonas aeruginosa'),
('PA4568', 'rplU', '', '', 'Pseudomonas aeruginosa'),
('PA4597', 'oprJ', '', '', 'Pseudomonas aeruginosa'),
('PA4598', 'mexD', '', '', 'Pseudomonas aeruginosa'),
('PA4599', 'mexC', '', '', 'Pseudomonas aeruginosa'),
('PA4600', 'nfxB', '', '', 'Pseudomonas aeruginosa'),
('PA4661', 'pagL', '', '', 'Pseudomonas aeruginosa'),
('PA4671', 'rplY', '', '', 'Pseudomonas aeruginosa'),
('PA4700', '', '', 'PBP1b', 'Pseudomonas aeruginosa'),
('PA4748', 'tpiA', '', '', 'Pseudomonas aeruginosa'),
('PA4751', 'ftsH', '', '', 'Pseudomonas aeruginosa'),
('PA4773', 'speD2', '', '', 'Pseudomonas aeruginosa'),
('PA4774', 'speE2', '', '', 'Pseudomonas aeruginosa'),
('PA4775', '', '', '-', 'Pseudomonas aeruginosa'),
('PA4776', 'pmrA', '', '', 'Pseudomonas aeruginosa'),
('PA4777', 'pmrB', '', '', 'Pseudomonas aeruginosa'),
('PA4878', 'brlR', '', '', 'Pseudomonas aeruginosa'),
('PA4944', 'hfq', '', '', 'Pseudomonas aeruginosa'),
('PA4964', 'parC', '', '', 'Pseudomonas aeruginosa'),
('PA4967', 'parE', '', '', 'Pseudomonas aeruginosa'),
('PA5000', 'wapR', '', '', 'Pseudomonas aeruginosa'),
('PA5038', 'aroB', '', '', 'Pseudomonas aeruginosa'),
('PA5045', '', '', 'PBP1a', 'Pseudomonas aeruginosa'),
('PA5117', 'typA', '', '', 'Pseudomonas aeruginosa'),
('PA5199', 'amgS', '', '', 'Pseudomonas aeruginosa'),
('PA5200', 'amgR', '', '', 'Pseudomonas aeruginosa'),
('PA5235', 'glpT', '', '', 'Pseudomonas aeruginosa'),
('PA5332', 'crc', '', '', 'Pseudomonas aeruginosa'),
('PA5366', 'pstB', '', '', 'Pseudomonas aeruginosa'),
('PA5471', 'armZ', '', '', 'Pseudomonas aeruginosa'),
('PA5471.1', '', '', '-', 'Pseudomonas aeruginosa'),
('PA5485', 'ampDh2', '', '', 'Pseudomonas aeruginosa'),
('PA5513', 'poxA', '', '', 'Pseudomonas aeruginosa'),
('PA5514', '', '', '-', 'Pseudomonas aeruginosa'),
('PA5528', '', '', '-', 'Pseudomonas aeruginosa'),
('PA5542', 'PIB-1', '', '', 'Pseudomonas aeruginosa'),
('PA0355', 'pfpI', '', '', 'Pseudomonas aeruginosa'),
('PA0357', 'mutM', '', '', 'Pseudomonas aeruginosa'),
('PA0750', 'ung', '', '', 'Pseudomonas aeruginosa'),
('PA1816', 'dnaQ', '', '', 'Pseudomonas aeruginosa'),
('PA3002', 'mfd', '', '', 'Pseudomonas aeruginosa'),
('PA3620', 'mutS', '', '', 'Pseudomonas aeruginosa'),
('PA4366', 'sodB', '', '', 'Pseudomonas aeruginosa'),
('PA4400', 'mutT', '', '', 'Pseudomonas aeruginosa'),
('PA4468', 'sodM', '', '', 'Pseudomonas aeruginosa'),
('PA4609', 'radA', '', '', 'Pseudomonas aeruginosa'),
('PA4946', 'mutL', '', '', 'Pseudomonas aeruginosa'),
('PA5147', 'mutY', '', '', 'Pseudomonas aeruginosa'),
('PA5344', 'oxyR', '', '', 'Pseudomonas aeruginosa'),
('PA5443', 'uvrD', '', '', 'Pseudomonas aeruginosa'),
('PA5493', 'polA', '', '', 'Pseudomonas aeruginosa');

-- INSERT INTO resistoma_adquirido (locus, nombre_oficial, nombre_sinonimo) VALUES
-- ('1','175','175'),
-- ('1','175','175');

INSERT INTO locus_mlst (locus, official_name, synonym_name, species) VALUES
('PA0887','acsA','','Pseudomonas aeruginosa'),
('PA0025','aroE','','Pseudomonas aeruginosa'),
('PA3769','guaA','','Pseudomonas aeruginosa'),
('PA4946','mutL','','Pseudomonas aeruginosa'),
('PA2639','nuoD','','Pseudomonas aeruginosa'),
('PA1770','ppsA','','Pseudomonas aeruginosa'),
('PA0609','trpE','','Pseudomonas aeruginosa');

INSERT INTO virulence_gene (locus, official_name, synonym_name, species) VALUES
('PA2191','exoY','','Pseudomonas aeruginosa'),
('PA3841','exoS','','Pseudomonas aeruginosa'),
('PA14_51530','exoU','','Pseudomonas aeruginosa'),
('PA0044','exoT','','Pseudomonas aeruginosa'),
('PA0012','rhlR','','Pseudomonas aeruginosa'),
('PA0041','lasA','','Pseudomonas aeruginosa'),
('PA0465','pchD','','Pseudomonas aeruginosa'),
('PA0470','pchE','','Pseudomonas aeruginosa'),
('PA0471','pchF','','Pseudomonas aeruginosa'),
('PA0472','pchG','','Pseudomonas aeruginosa'),
('PA0705','mvfR','pqsR','Pseudomonas aeruginosa'),
('PA0996','phnB','pqsB','Pseudomonas aeruginosa'),
('PA0997','rhlI','','Pseudomonas aeruginosa'),
('PA0998','phnC','pqsC','Pseudomonas aeruginosa'),
('PA0999','phnD','pqsD','Pseudomonas aeruginosa'),
('PA1000','phnA','pqsA','Pseudomonas aeruginosa'),
('PA1001','phnE','pqsE','Pseudomonas aeruginosa'),
('PA1003','phnF','pqsH','Pseudomonas aeruginosa'),
('PA1006','exoS','','Pseudomonas aeruginosa'),
('PA1092','bfmR','','Pseudomonas aeruginosa'),
('PA1093','bfmS','','Pseudomonas aeruginosa'),
('PA1148','lasR','','Pseudomonas aeruginosa'),
('PA1245','fliC','flagellin','Pseudomonas aeruginosa'),
('PA1429','pcrV','','Pseudomonas aeruginosa'),
('PA1709','exoU','','Pseudomonas aeruginosa'),
('PA1710','exoY','','Pseudomonas aeruginosa'),
('PA1861','toxA','exotoxin A','Pseudomonas aeruginosa'),
('PA1911','plcN','non-hemolytic phospholipase C','Pseudomonas aeruginosa'),
('PA2196','plcH','hemolytic phospholipase C','Pseudomonas aeruginosa'),
('PA2300','algD','','Pseudomonas aeruginosa'),
('PA2303','algU','','Pseudomonas aeruginosa'),
('PA2591','aprA','alkaline protease','Pseudomonas aeruginosa'),
('PA3048','exoT','','Pseudomonas aeruginosa'),
('PA3476','pilQ','','Pseudomonas aeruginosa'),
('PA3477','pilB','','Pseudomonas aeruginosa'),
('PA3478','pilA','','Pseudomonas aeruginosa'),
('PA3479','pilC','','Pseudomonas aeruginosa'),
('PA3705','fleS','','Pseudomonas aeruginosa'),
('PA3706','fleR','','Pseudomonas aeruginosa'),
('PA3720','fleQ','','Pseudomonas aeruginosa'),
('PA4213','phzF1','','Pseudomonas aeruginosa'),
('PA4214','phzE1','','Pseudomonas aeruginosa'),
('PA4215','phzD1','','Pseudomonas aeruginosa'),
('PA4216','phzC1','','Pseudomonas aeruginosa'),
('PA4217','phzB1','','Pseudomonas aeruginosa'),
('PA4218','phzA1','','Pseudomonas aeruginosa'),
('PA4290','vfr','','Pseudomonas aeruginosa'),
('PA4775','pvdS','','Pseudomonas aeruginosa');

INSERT INTO hypermutation_gene (locus, official_name, synonym_name, species) VALUES
('PA3774','mutS','','Pseudomonas aeruginosa'),
('PA3611','mutL','','Pseudomonas aeruginosa'),
('PA1864','uvrD','','Pseudomonas aeruginosa'),
('PA4299','mutT','nudB','Pseudomonas aeruginosa'),
('PA0704','dinB','imuB','Pseudomonas aeruginosa'),
('PA2041','lexA','','Pseudomonas aeruginosa'),
('PA3348','mutY','','Pseudomonas aeruginosa'),
('PA1846','mutM','fpg','Pseudomonas aeruginosa'),
('PA3630','mutH','','Pseudomonas aeruginosa'),
('PA0421','recA','','Pseudomonas aeruginosa'),
('PA0661','recG','','Pseudomonas aeruginosa'),
('PA4933','recN','','Pseudomonas aeruginosa'),
('PA3199','sbcD','','Pseudomonas aeruginosa'),
('PA3198','sbcC','','Pseudomonas aeruginosa'),
('PA4546','radA','','Pseudomonas aeruginosa'),
('PA0001','rpoS','','Pseudomonas aeruginosa'),
('PA0778','nrdA','','Pseudomonas aeruginosa'),
('PA0779','nrdB','','Pseudomonas aeruginosa'),
('PA5346','nrdD','','Pseudomonas aeruginosa'),
('PA1979','nth','endonuclease III','Pseudomonas aeruginosa'),
('PA2253','ung','uracil-DNA glycosylase','Pseudomonas aeruginosa'),
('PA1120','xthA','exonuclease III','Pseudomonas aeruginosa'),
('PA4680','polA','DNA polymerase I','Pseudomonas aeruginosa'),
('PA1329','polB','DNA polymerase II','Pseudomonas aeruginosa'),
('PA0927','polC','DNA polymerase III','Pseudomonas aeruginosa'),
('PA3031','polD','DNA polymerase IV','Pseudomonas aeruginosa'),
('PA4582','polE','DNA polymerase V','Pseudomonas aeruginosa');

INSERT INTO invitro_serotype (invitro_value) VALUES
('O1'),
('O2'),
('O3'),
('O4'),
('O5'),
('O6'),
('O7'),
('O8'),
('O9'),
('O10'),
('O11'),
('O12'),
('O13'),
('O14'),
('O15'),
('O16'),
('O17'),
('O18'),
('O19'),
('O20'),
('None'),
('Autoagglutination');

INSERT INTO assembler (assembler_name) VALUES 
('assembler_name_1'),
('assembler_name_2'),
('assembler_name_3');

INSERT INTO file_path (isolate_id, fastq_path, denovo_assembly_path, assembler) VALUES
(1,'/home/micro/secuencias/Proyecto001/fasta_files/','/home/micro/secuencias/Proyecto001/assembly_files/',1);